"""Add notification settings table

Revision ID: add_notification_settings
Revises: 398068dc3f6a
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_notification_settings'
down_revision = '398068dc3f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_updates_in_app', sa.Boolean(), nullable=True),
    sa.Column('job_updates_email', sa.Boolean(), nullable=True),
    sa.Column('training_alerts_in_app', sa.Boolean(), nullable=True),
    sa.Column('training_alerts_email', sa.Boolean(), nullable=True),
    sa.Column('application_status_updates_in_app', sa.Boolean(), nullable=True),
    sa.Column('application_status_updates_email', sa.Boolean(), nullable=True),
    sa.Column('saved_job_training_reminders_in_app', sa.Boolean(), nullable=True),
    sa.Column('saved_job_training_reminders_email', sa.Boolean(), nullable=True),
    sa.Column('system_notifications_in_app', sa.Boolean(), nullable=True),
    sa.Column('system_notifications_email', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###