"""add_job_fields_industry_experience_company_size

Revision ID: dc9ccc04ae01
Revises: 398068dc3f6a
Create Date: 2025-07-18 18:21:15.799604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9ccc04ae01'
down_revision: Union[str, None] = '398068dc3f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issuing_organization', sa.String(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('credential_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_id'), ['id'], unique=False)

    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_id'), ['id'], unique=False)

    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hobbies_id'), ['id'], unique=False)

    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_id'), ['id'], unique=False)

    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_experiences_id'), ['id'], unique=False)

    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('talent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['talent_id'], ['talents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_jobs_id'), ['id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company_size', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('highlights', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('highlights')
        batch_op.drop_column('company_size')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('industry')

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_jobs_id'))

    op.drop_table('saved_jobs')
    with op.batch_alter_table('work_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_experiences_id'))

    op.drop_table('work_experiences')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_id'))

    op.drop_table('languages')
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hobbies_id'))

    op.drop_table('hobbies')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_id'))

    op.drop_table('education')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_id'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
