name: climbr
description: Climbr — career platform for African talent
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5

  # Routing
  go_router: ^14.2.0

  # Motion
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
